- src:     elao.acl
  version: 1.0

- src:     elao.apt
  version: 1.0

- src:     elao.curl
  version: 1.0

- src:     elao.env
  version: 1.0

- src:     elao.motd
  version: 1.0

- src:     elao.env
  version: 1.0

- src:     elao.files
  version: 1.0

- src:     elao.gem
  version: 1.0

- src:     elao.git
  version: 1.0

- src:     elao.grafana
  version: 1.0

- src:     elao.hugo
  version: 1.0

- src:     elao.influxdb
  version: 1.0

- src:     elao.logio
  version: 1.0

- src:     elao.make
  version: 1.0

- src:     elao.mailcatcher
  version: 1.0

- src:     elao.nginx
  version: 1.0

- src:     elao.nodejs
  version: 1.0

- src:     elao.npm
  version: 1.0

- src:     elao.ohmyzsh
  version: 1.0

- src:     elao.phpmyadmin
  version: 1.0

- src:     elao.pip
  version: 1.0

- src:     elao.python
  version: 1.0

- src:     elao.ruby
  version: 1.0

- src:     elao.shorewall
  version: 1.0

- src:     elao.supervisor
  version: 1.0

- src:     elao.ssh
  version: 1.0

- src:     elao.timezone
  version: 1.0

- src:     elao.zsh
  version: 1.0


